return {
	{
		"tris203/precognition.nvim",
		keys = {
			{
				"<leader><leader>P",
				function()
					require("precognition").peek()
				end,
				desc = "Toggle Precognition",
			},
		},
		opts = {
			startVisible = false,
			-- showBlankVirtLine = true,
			-- highlightColor = { link = "Comment" },
			-- hints = {
			--      Caret = { text = "^", prio = 2 },
			--      Dollar = { text = "$", prio = 1 },
			--      MatchingPair = { text = "%", prio = 5 },
			--      Zero = { text = "0", prio = 1 },
			--      w = { text = "w", prio = 10 },
			--      b = { text = "b", prio = 9 },
			--      e = { text = "e", prio = 8 },
			--      W = { text = "W", prio = 7 },
			--      B = { text = "B", prio = 6 },
			--      E = { text = "E", prio = 5 },
			-- },
			-- gutterHints = {
			--     G = { text = "G", prio = 10 },
			--     gg = { text = "gg", prio = 9 },
			--     PrevParagraph = { text = "{", prio = 8 },
			--     NextParagraph = { text = "}", prio = 8 },
			-- },
			-- disabled_fts = {
			--     "startify",
			-- },
		},
	},
	{
		"m4xshen/hardtime.nvim",
		event = "VeryLazy",
		keys = { "<leader><leader>H", "<cmd>Hardtime toggle<cr>", desc = "Toggle Hardtime" },
		opts = {
			max_time = 1000,
			max_count = 5,
			disable_mouse = false,
			hint = true,
			notification = true,
			allow_different_key = false,
			resetting_keys = {
				["1"] = { "n", "x" },
				["2"] = { "n", "x" },
				["3"] = { "n", "x" },
				["4"] = { "n", "x" },
				["5"] = { "n", "x" },
				["6"] = { "n", "x" },
				["7"] = { "n", "x" },
				["8"] = { "n", "x" },
				["9"] = { "n", "x" },
				["c"] = { "n" },
				["C"] = { "n" },
				["d"] = { "n" },
				["x"] = { "n" },
				["X"] = { "n" },
				["y"] = { "n" },
				["Y"] = { "n" },
				["p"] = { "n" },
				["P"] = { "n" },
			},
			restricted_keys = {
				["h"] = {},
				["j"] = { "n", "x" },
				["k"] = { "n", "x" },
				["l"] = {},
				["-"] = { "n", "x" },
				["+"] = { "n", "x" },
				["gj"] = { "n", "x" },
				["gk"] = { "n", "x" },
				["<CR>"] = { "n", "x" },
				["<C-M>"] = { "n", "x" },
				["<C-N>"] = { "n", "x" },
				["<C-P>"] = { "n", "x" },
			},
			disabled_keys = {
				["<Up>"] = { "" },
				["<Down>"] = { "" },
				["<Left>"] = { "" },
				["<Right>"] = { "" },
			},
			disabled_filetypes = {
				"qf",
				"netrw",
				"neo-tree",
				"neo-tree-popup",
				"lazy",
				"mason",
				"help",
				"noice",
				"toggleterm",
				"undotree",
				"diff",
				"sagarename",
				"sagafinder",
				"sagaoutline",
				"dapui_stacks",
				"dapui_scopes",
				"dapui_watches",
			},
		},
	},
}
